### ISSUE TITLE
Plan for the Binary chapter 

### ISSUE THREAD

**Issue by tchoi8** [tchoi8/handmadecomputer#7]
- this chapter is especially overwhelming to the readers. great feedback in Kyle Mcdonald's comments. https://github.com/tchoi8/handmadecomputer/issues/5 
- This chapter can be all rendered in pen drawings. 
  ~~\- Something like "Now, we are going to really build a computer with electronics" would be helpful to transition.~~
- This maybe a good point to introduce the Transistor and TTL. Some parts of https://github.com/tchoi8/handmadecomputer/tree/master/TTL can be used.
-  Clearly indicate this!  Output = Hands. Thumbs up = 1/ True/ On, Thumbs down = 0/ False/ Off. Jon Moeller's comments are super precise about what's currently confusing. "0 and 1 is like voltage level, machine code, it's how we interface with objects" https://github.com/tchoi8/handmadecomputer/issues/1  
- Defining TTL - draw two transistors side by side. with their arms around each other. Transistor friends! 
- This part "0+0=0 0+1=1 1+0=1 1+1=10 (2 in decimal notation)" is especially confusing. Need to explain that binary numbers are read as One Zero, as opposed to Ten. https://camo.githubusercontent.com/f03a0132e2ef1a68a7f5944d52a1d0e7649ac6ca/68747470733a2f2f6661726d362e737461746963666c69636b722e636f6d2f353832362f32313035353730323635315f316666353461383765395f622e6a70672532303d36303058 this image may need to come earlier. 
- use the concept of Repetition and Abstraction to explain why Universal gate/ twisting the NAND gates to make XOR gate is important or relevant...

**Comment by hxrts** [comment]
- I agree, the binary chapter does get a little intense. I did some photoshop edits to space things out but it's hard for me to do any significant editing once things are rendered to images. If you're planning to convert a significant portion of the writing to pen, I would suggest trying to get the text fairly close to where you want it first so I can do an edit for grammar. Doing this after the fact gets a bit labor intensive.
- One of the only comments I left was a suggestion to briefly describe what a transistor does, so I'm glad that's being addressed.
- Try not to go into too much depth with TTL. If we add much more to this piece it's libel to become a book.
- I like the venn diagrams, they're one of the few things laymen readers have to anchor their understanding. I'd say if you're looking to consolidate we could make a single reference image that has each gate symbol, its truth table, and the corresponding venn diagram together.
- If you're going to explain binary numbers, again, I'd keep it concise. Try to keep it to a single reference diagram that they can scroll back to if needed. reference diagrams [here](http://www.mathmaniacs.org/lessons/01-binary/Magic_Trick/counting.gif) and [here](http://4.bp.blogspot.com/-_W4FaOVZIfg/VVp3KwCKRfI/AAAAAAAAEC4/WLRhrRjGWys/s1600/binari2.gif)
- Also, I like your handwriting done on the tablet (I assume), but it looks a bit odd having both pen and the digital handwriting in the same image. We might be able to get away with it if they were more distinct from one another, but they're only just dissimilar enough that I start to focus on what's going on with the image, rather than the story.

**Comment by tchoi8** [comment]
- sure. now ill do everything on text and (maybe do some edits on photoshop) but check with you  before making new drawings or rendering final images. 
- yes. i can make sure to introduce the transistor briefly
- ok . not diving in the sea of TTL
- ok  will investigate how venn diagrams can be helpful and don't overwhelm with graphics 
- cool 
- yes. im doing things on tablet to quickly sketch out an idea. Doing it again with real pen on paper is not hard, once we are happy with the content and layout.

**Comment by tchoi8** [comment]
Proposing new structure for this chapter 
1. Define 1-bit computer (Adder + Memory + Clock)
2. Introduce electronic friends 
3. Binary logic (AND, NAND)
4. 1-bit computer with NAND logic gates 
5. Summary 

Notes on the Structure 
1. "Now let's make a computer! Wait, what is a computer? Computer can do math (like adding, subtracting, multiplying), remember information over time. It also has clocks which is very important. Computers, even in itssimpliest form will have all of these functionalities. We are going to use electronics to make it into a circuit".  
2. "Say Hi to the electronic friends!" Meet Breadboard, Battery (Voltage and Current), Switch (On and Off), Transistor (NPN), LED and Push button and potentiometer. TTL stands for "Transistor Transistor Logic" which is a combination of Transistors to create logical operations. 
3. Break from the technical details, change tones slightly. Brief mention of Claude Shannon's paper on switching circuits and George Boole' logic. Explain Binary with Thumbs up & down and Venn Diagram. Also introduce Integrated Circuit and the idea of abstraction here.  
4. Step by Step of making a 1-bit computer. Using the universal Logic of NAND & NOR. Interactive components come in here.  
5. Summary and transition to next chapter. "This is how computers work on the conceptual level. However, 1-bit computer can not do alot of useful computation, and it can't even be programmed per se. Thus we need to look at how modern computers use abstraction and repeptition of Logic to make something that is arguably close to Computer".

**Comment by hxrts** [comment]
added these comments to gdoc. closing
